INCLUDES=..;$(IFSPATH)\inc\IFS\WNET

MSC_WARNING_LEVEL=/W3

SOURCES=Driver.cpp \
       	FilFile.cpp \
	    CFilterBase.cpp \
	    CFilterBlacklist.cpp \
        CFilterCallback.cpp \
       	CFilterCipherCTR.cpp \
       	CFilterCipherCFB.cpp \
		CFilterCipherEME.cpp \
       	CFilterContext.cpp \
       	CFilterControl.cpp \
       	CFilterDirectory.cpp \
       	CFilterEngine.cpp \
       	CFilterEntity.cpp \
       	CFilterFastIo.cpp \
       	CFilterFile.cpp \
       	CFilterHeader.cpp \
       	CFilterHeaderCache.cpp \
       	CFilterCipherManager.cpp \
       	CFilterNormalizer.cpp \
       	CFilterPath.cpp \
       	CFilterRandomizer.cpp \
       	CFilterVolume.cpp\
		CFilterWiper.cpp\
		CWipePattern.cpp\
		CFilterProcess.cpp\
		CFilterAppList.cpp\
		CFilterTracker.cpp\
		CFilterLuidCont.cpp\
       	version.rc
       
       

       	
       	

